#===============================================
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# ByÔºözwrt
#===============================================

name: ÁºñËØëPhicomm-N1Âõ∫‰ª∂

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: configs/Phicomm-N1/feeds.conf.default
  CONFIG_FILE: configs/Phicomm-N1/Phicomm-N1.config
  DIY_P1_SH: configs/Phicomm-N1/diy-part1.sh
  DIY_P2_SH: configs/Phicomm-N1/diy-part2.sh
  CLASH_KERNEL: arm64
  UPLOAD_RELEASE: true
  FILE_NAME: ROOTFS
  PRODUCT_NAME: Phicomm-N1

jobs:
  Build:
    runs-on: ubuntu-22.04

    outputs:
      author: ${{ steps.clone.outputs.author }}
      date: ${{ steps.clone.outputs.date }}
      commit: ${{ steps.clone.outputs.commit }}
      hash: ${{ steps.clone.outputs.hash }}

    steps:
    - name: ÂáÜÂ§áÂÆåÊàê
      uses: actions/checkout@v3

    - name: Ê£ÄÊü•ÊúçÂä°Âô®ÊÄßËÉΩ
      run: |
        cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c > CPU
        cat /proc/cpuinfo | grep "cpu cores" | uniq >> CPU
        sed -i 's|[[:space:]]||g; s|^.||' CPU && sed -i 's|CPU||g; s|pucores:||' CPU
        CPUNAME="$(awk 'NR==1' CPU)" && CPUCORES="$(awk 'NR==2' CPU)"
        curl -k --data chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" --data "text=Phicomm-N1 Ê≠£Âú®‰ΩøÁî® [${CPUNAME} CPU]  [${CPUCORES} Ê†∏ÂøÉ] [lede] Ê∫êÁ†Å ÁºñËØëÂõ∫‰ª∂,ËØ∑ËÄêÂøÉÁ≠âÂæÖ..." "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${MSG}"

    - name: ÂàùÂßãÂåñÁ≥ªÁªüÁéØÂ¢É
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(cat $GITHUB_WORKSPACE/diy/depends-ubuntu-2204)
        pip install aligo
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: ÂÖãÈöÜÊ∫ê‰ª£Á†Å
      id: clone
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        author=$(git show -s --date=short --format="‰ΩúËÄÖ: %an")
        date=$(git show -s --date=short --format="Êó∂Èó¥: %ci")
        commit=$(git show -s --date=short --format="ÂÜÖÂÆπ: %s")
        hash=$(git show -s --date=short --format="hash: %H")
        echo "author=$author" >> $GITHUB_ENV
        echo "author=$author" >> $GITHUB_OUTPUT
        echo "date=$date" >> $GITHUB_ENV
        echo "date=$date" >> $GITHUB_OUTPUT
        echo "commit=$commit" >> $GITHUB_ENV
        echo "commit=$commit" >> $GITHUB_OUTPUT
        echo "hash=$hash" >> $GITHUB_ENV
        echo "hash=$hash" >> $GITHUB_OUTPUT

    - name: Âä†ËΩΩËá™ÂÆö‰πâÊ∫êÁ†Å
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        chmod +x $DIY_P1_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P1_SH

    - name: ÂÆâË£Ö Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Âä†ËΩΩËá™ÂÆö‰πâÈÖçÁΩÆ
      run: |
        [ -e files ] && mv files openwrt/files
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x $GITHUB_WORKSPACE/diy/*.sh
        chmod +x $DIY_P2_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: ‰∏ãËΩΩËΩØ‰ª∂ÂåÖ
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: ÁºñËØëÂõ∫‰ª∂
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: Ê£ÄÊü•Á©∫Èó¥‰ΩøÁî®ÊÉÖÂÜµ
      if: (!cancelled())
      run: df -hT

    - name: Êï¥ÁêÜÂõ∫‰ª∂Êñá‰ª∂
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd $GITHUB_WORKSPACE/openwrt/bin/packages
        tar -zcvf Packages.tar.gz ./*
        cp Packages.tar.gz $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        cd $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
        rm -rf Packages.tar.gz feeds.buildinfo openwrt-armvirt-64-generic-kernel.bin openwrt-armvirt-64-generic.manifest sha256sums version.buildinfo
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

#    - name: ÂèëÂ∏ÉÂõ∫‰ª∂
#      id: release
#      uses: ncipollo/release-action@v1
#      if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success'
#      with:
#        name: ${{ env.DATE }} üö´ „Äå${{ env.FILE_NAME }}Â∫ïÂåÖ„Äç
#        allowUpdates: true
#        removeArtifacts: true
#        tag: ${{ env.FILE_NAME }}
#        token: ${{ secrets.GH_TOKEN }}
#        artifacts: ${{ env.FIRMWARE }}/*
#        body: |
#          **This is Temporary Firmware for Armvirt 64**
#          ### üìí Âõ∫‰ª∂‰ø°ÊÅØ
#          - üíª ËøôÊòØ ARMv8 Â∫ïÂåÖÔºåÈùûÂÆåÊï¥Âõ∫‰ª∂Ôºå‰∏çÂèØÁõ¥Âà∑
#          - üöÄ Áõ¥Âà∑Âõ∫‰ª∂ÁÇπÂáªÊ≠§Â§ÑË∑≥ËΩ¨‚û¶[${{ env.PRODUCT_NAME }}](https://github.com/zwrt/OpenWrt/releases/tag/${{ env.PRODUCT_NAME }})Âç≥ÂèØ‰∏ãËΩΩ
#          - ‚öΩ Âõ∫‰ª∂Ê∫êÁ†Å: ${{ env.REPO_URL }}
#          - üíù Ê∫êÁ†ÅÂàÜÊîØ: ${{ env.REPO_BRANCH }}
#          ### üßä Âõ∫‰ª∂ÁâàÊú¨
#          - Âõ∫‰ª∂ÁºñËØëÂâçÊúÄÂêé‰∏ÄÊ¨°‚û¶[‰∏ªÊ∫êÁ†Å](${{ env.REPO_URL }})Êõ¥Êñ∞ËÆ∞ÂΩï
#          - ${{ env.author }}
#          - ${{ env.date }}
#          - ${{ env.commit }}
#          - ${{ env.hash }}

#  Package:
#    needs: [Build]
#    runs-on: ubuntu-22.04

#    env:
#      author: ${{ needs.Build.outputs.author }}
#      date: ${{ needs.Build.outputs.date }}
#      commit: ${{ needs.Build.outputs.commit }}
#      hash: ${{ needs.Build.outputs.hash }}

#    steps:
#    - name: ÂáÜÂ§áÂÆåÊàê
#      uses: actions/checkout@v3

#    - name: ËÆæÁΩÆÊó•Êúü
#      run: |
#        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

#    - name: ÂàùÂßãÂåñÁ≥ªÁªüÁéØÂ¢É
#      env:
#        DEBIAN_FRONTEND: noninteractive
#      run: |
#        docker rmi $(docker images -q)
#        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
#        sudo -E apt-get -y update
#        sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204)
#        pip install aligo
#        sudo -E apt-get -y autoremove --purge
#        sudo -E apt-get -y clean
#        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: ÊâìÂåÖopenwrt
      uses: ophub/flippy-openwrt-actions@main
      if: (!cancelled())
      env:
        OPENWRT_ARMVIRT: openwrt/bin/targets/*/*/*.tar.gz
        PACKAGE_SOC: s905d
        WHOAMI: TIAmo
        OPENWRT_VER: ${{ github.event.inputs.openwrt_version }}
        DISTRIB_REVISION: ${OPENWRT_VER} (By @TIAmo build $(TZ=UTC-8 date "+%Y-%m-%d %H:%M"))
        KERNEL_REPO_URL: https://github.com/zwrt/kernel/releases/tag/kernel_stable
        KERNEL_VERSION_NAME: 5.15.13
        KERNEL_AUTO_LATEST: true
        GZIP_IMGS: .gz
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Êï¥ÁêÜÂõ∫‰ª∂Êñá‰ª∂
      run: |
        cd /opt/openwrt_packit/output
        rm -rf openwrt-armvirt-64-generic-rootfs.tar.gz *.sha
        echo "PACKAGED_OUTPUTPATH=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: ÂèëÂ∏ÉÂõ∫‰ª∂
      if: env.PACKAGED_STATUS == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.DATE }} üö´ „Äå${{ env.PRODUCT_NAME }}Âõ∫‰ª∂„Äç
        allowUpdates: true
        removeArtifacts: true
        tag: ${{ env.PRODUCT_NAME }}
        token: ${{ secrets.GH_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        body: |
          **This is OpenWrt Firmware for Armvirt 64**
          ### üìí Âõ∫‰ª∂‰ø°ÊÅØ
          - üíª ËøôÊòØ ${{ env.PRODUCT_NAME }} Âõ∫‰ª∂ÔºåÈõÜÊàê‰∏Ä‰∫õÊó•Â∏∏Â∏∏Áî®Êèí‰ª∂
          - ‚öΩ Âõ∫‰ª∂Ê∫êÁ†Å: ${{ env.REPO_URL }}
          - üíù Ê∫êÁ†ÅÂàÜÊîØ: ${{ env.REPO_BRANCH }}
          - üåê ÈªòËÆ§Âú∞ÂùÄ: 192.168.1.4
          - üîë ÈªòËÆ§ÂØÜÁ†Å: password
          ### üçª ÂÆâË£Ö‰∏éÊõ¥Êñ∞
          - Áî®Êèí‰ª∂ÂÆâË£Ö: Á≥ªÁªü ‚Üí Êô∂Êô®ÂÆùÁõí ‚Üí ÂÆâË£Ö OpenWrt ‚Üí ÈÄâÊã©ÂûãÂè∑ ‚Üí ÂÆâË£Ö
          - Áî®ÂëΩ‰ª§ÂÆâË£Ö: UÁõòÂêØÂä®ÊàêÂäüÂêéËæìÂÖ•ÂëΩ‰ª§ `openwrt-install-amlogic` ÊåâÁÖßËã±ÊñáÊèêÁ§∫ÂÜôÂÖ•Âà∞ emmc
          - Áî®Êèí‰ª∂Êõ¥Êñ∞: Á≥ªÁªü ‚Üí Êô∂Êô®ÂÆùÁõí ‚Üí Âú®Á∫ø‰∏ãËΩΩÊõ¥Êñ∞ ‚Üí ÂÆåÊï¥Êõ¥Êñ∞ÂÖ®Á≥ªÁªü
          - Áî®ÂëΩ‰ª§Êõ¥Êñ∞: ‰∏ä‰º†Âõ∫‰ª∂Âà∞ `/mnt/mmcblk2p4` ÁõÆÂΩïÔºåËæìÂÖ•ÂëΩ‰ª§ `openwrt-update-amlogic` Âç≥ÂèØÊõ¥Êñ∞
          - Ê≥®ÊÑè: Â¶ÇÈùû `amlogic` Âπ≥Âè∞ÔºåËØ∑Â∞ÜÂÖ∂Êõ¥Êîπ‰∏∫ÂØπÂ∫îÂπ≥Âè∞ `rockchip` `allwinner`
          - ÈÉ®ÂàÜÂ∏∏ËßÅÈóÆÈ¢òÂèäÊ≥®ÊÑè‰∫ãÈ°πËØ∑ÂèÇËÄÉÊÅ©Â±±ËÆ∫ÂùõFÂ§ß‚û¶[ÊúÄÊñ∞Â∏ñ](https://www.right.com.cn/forum/thread-4076037-1-1.html)
          ### üßä Âõ∫‰ª∂ÁâàÊú¨
          - Âõ∫‰ª∂ÁºñËØëÂâçÊúÄÂêé‰∏ÄÊ¨°‚û¶[‰∏ªÊ∫êÁ†Å](${{ env.REPO_URL }})Êõ¥Êñ∞ËÆ∞ÂΩï
          - ${{ env.author }}
          - ${{ env.date }}
          - ${{ env.commit }}
          - ${{ env.hash }}

    - name: ÁîµÊä•ÈÄöÁü•
      run: |
        MSG="
        ÁºñËØëÊó∂Èó¥Ôºö${{ env.DATE }}
        Phicomm-N1ÁºñËØëÂÆåÊàê
        "
        curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=${MSG}"

    - name: Â§çÂà∂Êñá‰ª∂
      run: |
        mkdir -p ./ARM_Out/
        cp -a ${{ env.PACKAGED_OUTPUTPATH }}/* ./ARM_Out/
        cd ARM_Out
        mv openwrt_s905d_n1*.img.gz N1-$(date +%Y%m%d).img.gz
        zip -r $GITHUB_WORKSPACE/ARM_Out/N1-$(date +%Y%m%d).zip N1-$(date +%Y%m%d).img.gz

    - name: ‰∏ä‰º†Aliyun
      run: | 
        echo "ËØ∑Ëá™Âä®ÂøΩÁï•META-INFÊñá‰ª∂Â§π„ÄÇ" > ÂøΩÁï•META-INFÊñá‰ª∂Â§π.txt
        zip_files=$(find $GITHUB_WORKSPACE/ARM_Out/N1* -name '*.zip' -type f -print | tr '\n' ';' | sed 's/;$//')
        echo "Zip files: ${zip_files}"
        chmod +x $GITHUB_WORKSPACE/diy/aliupload.py
        python $GITHUB_WORKSPACE/diy/aliupload.py --token "${{ secrets.ALIYUN_TOKEN }}" --uploadFloder "OpenWrt/N1" --file "${zip_files}"
    
    - name: Âà†Èô§ËøêË°åËÆ∞ÂΩï
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 0
        keep_minimum_runs: 3
